_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.19.9
            "6": 4.51.2
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
BATCH_SIZE:
    value: 8
EPOCHS:
    value: 2
checkpoints_dir:
    value: ./outputs/checkpoints
class_mapping:
    value:
        "0": real
        "1": fake
data_dir:
    value: ./data
dropout:
    value: 0.3
early_stopping_patience:
    value: 5
embed_dim:
    value: 768
eval_on_test:
    value: true
false_csv:
    value: ./data/fake.csv
hidden_dim:
    value: 256
lr:
    value: 0.0003
max_length:
    value: 512
model_name:
    value: distilbert-base-uncased
num_workers:
    value: 4
output_dim:
    value: 2
output_dir:
    value: ./outputs
pin_memory:
    value: true
plots_dir:
    value: ./outputs/plots
random_state:
    value: 42
save_best_model:
    value: true
stride:
    value: 128
train_test_split:
    value: 0.01
train_val_split:
    value: 0.2
true_csv:
    value: ./data/true.csv
use_wandb:
    value: true
wandb_entity:
    value: chen-ben968-benchen
wandb_project:
    value: fake-news-detector
wandb_run_name:
    value: distilbert-embeddings
